COMPONENT=OtaBasestationAppC

CFLAGS += -DTOSH_DATA_LENGTH=40

PFLAGS += -I$(TOSDIR)/lib/net/tymo -I$(TOSDIR)/lib/net/tymo/dymo -I$(TOSDIR)/lib/net/tymo/mh
PFLAGS += -I$(TOSDIR)/lib/net/Deluge

include $(MAKERULES)

