#!/usr/bin/env python

# First thing, append the utils directory to the search path.
import sys, os, subprocess, time
utils_dir = os.path.abspath(os.path.dirname(__file__)) + '/utils'
sys.path.append(utils_dir)

# Now we can import the basestation module
import basestation

# Now add the snee utilities to PATH
os.environ['PATH'] = utils_dir + ':' + os.environ['PATH']

# Discover the environment variables
basestation = basestation.find_basestation()
source = 'serial@' + basestation + ':115200'

# deploy the metadata collector basestion
print "Deploying the metadata collector basestion"
os.chdir(os.path.abspath(os.path.dirname(__file__)) + '/../nesC/MetadataCollectorBasestation')
subprocess.call(['make', 'telosb', 'install,' + sys.argv[3], 'bsl,' + basestation])

# start sending metadata
print "Start collecting metadata"
subprocess.call(['python', utils_dir+'/cmd-srvr', source, '--start'])

# collect metadata
print "Collecting..."
subprocess.call(['python', utils_dir+'/metadata-collector', source, sys.argv[1], sys.argv[2]])

# stop sending metadata
print "Stop collecting metadata"
subprocess.call(['python', utils_dir+'/cmd-srvr', source, '--stop'])

# parse text file and convert to xml
print "Processing..."
subprocess.call(['python', utils_dir+'/snee-txt-to-xml', sys.argv[1], sys.argv[2]])

print "Waiting to make sure all motes have stopped"
time.sleep(10)

# boot into ota
print "Switch motes to OTA server"
subprocess.call(['python', utils_dir+'/cmd-srvr', source, '--reprogram', '1'])

# wait for motes to boot into ota before continuing
print "Waiting to make sure all motes have received the reprogram command"
time.sleep(10)

# deploy the OTA basestion
print "Deploying the OTA basestion"
os.chdir(os.path.abspath(os.path.dirname(__file__)) + '/../OtaBasestation')
subprocess.call(['make', 'telosb', 'install,' + sys.argv[3], 'bsl,' + basestation])