#!/usr/bin/env python

# First thing, append the utils directory to the search path.
import sys, os, subprocess, time
utils_dir = os.path.dirname(__file__) + '/utils'
sys.path.append(utils_dir)

# Now we can import the basestation module
import basestation

# Now add the snee utilities to PATH
os.environ['PATH'] = utils_dir + ':' + os.environ['PATH']

# Discover the environment variables
basestation = basestation.find_basestation()
source = 'serial@' + basestation + ':115200'

# disseminate a reprogram command; switch to query fragment
subprocess.call(['python', utils_dir+'cmd-srvr', source, '--reprogram', '2'])

time.sleep(30)

# disseminate the start command
subprocess.call(['python', utils_dir+'cmd-srvr', source, '--start'])
