#!/usr/bin/env python

# First thing, append the utils directory to the search path.
import sys, os, subprocess, time
utils_dir = os.path.dirname(__file__) + '/utils'
sys.path.append(utils_dir)

# Now we can import the basestation module
import basestation

# Now add the snee utilities to PATH
os.environ['PATH'] = utils_dir + ':' + os.environ['PATH']

# Discover the environment variables
basestation = basestation.find_basestation()
source = 'serial@' + basestation + ':115200'

# disseminate the stop command
subprocess.call(['python', utils_dir+'cmd-srvr', source, '--stop'])

# sleep for 10 seconds
time.sleep(10)

# disseminate a reprogram command; switch to ota
subprocess.call(['python', utils_dir+'cmd-srvr', source, '--reprogram', '1'])

time.sleep(20)

# reprogram the gateway mote to ota basestation
os.chdir(os.path.dirname(__file__) + '/../nesC/OtaBasestation')
subprocess.call(['make', 'telosb', 'install,' + sys.argv[1], 'bsl,' + basestation])
