#!/usr/bin/env python

# First thing, append the utils directory to the search path.
import sys, os, subprocess, time
utils_dir = os.path.dirname(__file__) + '/utils'
sys.path.append(utils_dir)

# Now we can import the basestation module
import basestation
from error_handling import handleReturnCode

# Now add the snee utilities to PATH
os.environ['PATH'] = utils_dir + ':' + os.environ['PATH']

# Discover the environment variables
basestation = basestation.find_basestation()
source = 'serial@' + basestation + ':115200'

print "Disseminate the stop command"
subprocess.call(['python', utils_dir+'/cmd-srvr', source, '--stop'])

print 'Waiting to make sure all nodes are in stop state'
time.sleep(10)

print "Disseminate a reprogram command; switch to ota"
subprocess.call(['python', utils_dir+'/cmd-srvr', source, '--reprogram', '1'])

print 'Waiting to make sure all nodes are running ota'
time.sleep(30)

print "Reprogram the gateway mote to ota basestation"
os.chdir(os.path.dirname(__file__) + '/../nesC/OtaBasestation')
retcode = subprocess.call(['make', 'telosb', 'install,' + sys.argv[1], 'bsl,' + basestation])
handleReturnCode(retcode, 'Couldn\'t install OTA basestation on mote')
