COMPONENT=OtaServerAppC
BOOTLOADER=tosboot

CFLAGS += -DSNEE_IMAGE_ID=1
CFLAGS += -DTOSH_DATA_LENGTH=40
CFLAGS += -I../tymo -I../tymo/dymo -I../tymo/mh
CFLAGS += -I../CommandServer

include $(MAKERULES)
