#!/usr/bin/env python

import sys, os, getopt

tosroot = os.getenv('TOSROOT')
motecom = os.getenv('MOTECOM')

collection_time = 5 * 60

# deploy the command server basestion
os.chdir(tosroot + '/apps/CommandServer')
os.execl('make telosb install,0 bsl,' + motecom)

# start sending metadata
os.execl('cmd-svr ' + motecom + ' --start')

# deploy the metadata collector basestion
os.chdir(tosroot + '/apps/MetadataCollector')
os.execl('make telosb install,0 bsl,' + motecom)

# run the metadata basestation
os.execl('oscilloscope ' + motecom + ' ' + str(collection_time))

# wait until all data has been collected
os.sleep(collection_time)

# execute the text-to-xml converter
os.execl('oscilloscope ' + motecom + ' ' + str(collection_time))

# deploy the command server basestion
os.chdir(tosroot + '/apps/CommandServer')
os.execl('make telosb install,0 bsl,' + motecom)

# stop collection
os.execl('cmd-svr ' + motecom + ' --stop')

# wait for the message to propogate
os.sleep(collection_time)

# boot into ota
os.execl('cmd-svr ' + motecom + ' --reprogram 2')