#!/usr/bin/env python

# First thing, append the utils directory to the search path.
import sys, os, subprocess, getopt
utils_dir = os.path.dirname(__file__) + '/utils'
sys.path.append(utils_dir)

# Now we can import the basestation module
import basestation

# Change to the utils directory
os.chdir(utils_dir)

# Discover the environment variables
basestation = basestation.find_basestation()
source = 'serial@' + basestation + ':115200'

# generate a list of mote ids
mote_ids = getopt.getopt(sys.argv[1:], '')[1]

#iterate over the mote ids to register the query fragment
for mote_id in mote_ids:
    subprocess.call(['./tos-ota', source, mote_id, '--erase', '2'])
