#!/usr/bin/env python

import sys, os, getopt, subprocess

tosroot = os.getenv('TOSROOT')
motecom = os.getenv('MOTECOM')
serial_port = os.getenv('SERIAL_PORT')

# deploy the metadata collector basestion
os.chdir(tosroot + '/apps/MetadataCollector')
subprocess.call(['make', 'telosb', 'install,1', 'bsl,' + serial_port])

# start sending metadata
os.chdir(tosroot + '/apps/CommandServer')
subprocess.call(['./cmd-srvr', motecom, '--start'])

# collect metadata
os.chdir(tosroot + '/apps/MetadataCollector')
subprocess.call(['./metadata-collector', motecom, sys.argv[1], sys.argv[2]])

# stop sending metadata
os.chdir(tosroot + '/apps/CommandServer')
subprocess.call(['./cmd-srvr', motecom, '--stop'])

# parse text file and convert to xml
os.chdir(tosroot + '/apps/SneeScripts')
subprocess.call(['./snee-txt-to-xml', sys.argv[1], sys.argv[2]])

# deploy the OTA basestion
os.chdir(tosroot + '/apps/ota/otabasestation')
subprocess.call(['make', 'telosb', 'install,1', 'bsl,' + serial_port])

# boot into ota
os.chdir(tosroot + '/apps/CommandServer')
subprocess.call(['./cmd-srvr', motecom, '--reprogram', '1'])
