#!/usr/bin/env python

# First thing, append the utils directory to the search path.
import sys, os, subprocess
utils_dir = os.path.abspath(os.path.dirname(__file__)) + '/utils'
sys.path.append(utils_dir)

# Now we can import the basestation module
import basestation

# Now add the snee utilities to PATH
os.environ['PATH'] = utils_dir + ':' + os.environ['PATH']

# Discover the environment variables
basestation = basestation.find_basestation()
source = 'serial@' + basestation + ':115200'

# deploy the metadata collector basestion
os.chdir(os.path.abspath(os.path.dirname(__file__)) + '/../nesC/MetadataCollector')
subprocess.call(['make', 'telosb', 'install,' + sys.argv[3], 'bsl,' + basestation])

# start sending metadata
subprocess.call(['cmd-srvr', source, '--start'])

# collect metadata
subprocess.call(['metadata-collector', source, sys.argv[1], sys.argv[2]])

# stop sending metadata
subprocess.call(['cmd-srvr', source, '--stop'])

# parse text file and convert to xml
subprocess.call(['snee-txt-to-xml', sys.argv[1], sys.argv[2]])

# deploy the OTA basestion
os.chdir(os.path.abspath(os.path.dirname(__file__)) + '/../OtaBasestation')
subprocess.call(['make', 'telosb', 'install,' + sys.argv[3], 'bsl,' + basestation])

# boot into ota
subprocess.call(['cmd-srvr', source, '--reprogram', '1'])

# wait for motes to boot into ota before continuing
time.sleep(20)
