#!/usr/bin/env python

import os, time, subprocess

tosroot = os.getenv('TOSROOT')
motecom = os.getenv('MOTECOM')
serial_port = os.getenv('SERIAL_PORT')

os.chdir(os.getcwd() + '/utils')

# disseminate the stop command
subprocess.call(['./cmd-srvr', motecom, '--stop'])

# sleep for 10 seconds
time.sleep(10)

# disseminate a reprogram command; switch to ota
subprocess.call(['./cmd-srvr', motecom, '--reprogram', '1'])
