#!/usr/bin/env python

import sys, os, getopt

tosroot = os.getenv('TOSROOT')
motecom = os.getenv('MOTECOM')

# deploy the OTA basestion
os.chdir(tosroot + '/apps/ota/otabasestation')
os.execl('make telosb install,1 bsl,' + motecom)

# switch the ota client script folder
os.chdir(tosroot + '/apps/ota/otaclient')

# generate a list of mote ids
mote_ids = getopt.getopt(sys.argv[2:], '')[1]
#iterate over the mote ids to register the query fragment
for mote_id in mote_ids:
	os.execl('tos-ota ' + motecom + ' ' + mote_id + ' -i 3 ' + sys.argv[1])
	
# deploy the command server basestion
os.chdir(tosroot + '/apps/CommandServer')
os.execl('make telosb install,0 bsl,' + motecom)

# disseminate a reprogram command; switch to query fragment
os.execl('cmd-svr ' + motecom + ' --reprogram 3')