#!/usr/bin/env python

import sys, os, getopt

tosroot = os.getenv('TOSROOT')
motecom = os.getenv('MOTECOM')

#deploy the command server basestion
os.chdir(tosroot + '/apps/CommandServer')
os.execl('make telosb install,0 bsl,' + motecom)

os.execl('cmd-svr ' + motecom + ' --start')