#!/usr/bin/env python

import sys, os, getopt

tosroot = os.getenv('TOSROOT')
motecom = os.getenv('MOTECOM')

#deploy the command server basestion
os.chdir(tosroot + '/apps/CommandServer')
os.execl('make telosb install,0 bsl,' + motecom)

os.execl('cmd-svr ' + motecom + ' --stop')

# sleep for 10 seconds
time.sleep(10)

# disseminate a reprogram command; switch to ota
os.execl('cmd-svr ' + motecom + ' --reprogram 2')